import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
    // Generating a 9-conviction packet parses and re-serialises a dozen PDFs. It is not fast,
    // and the invariant checks deliberately re-read the generated BYTES rather than trusting
    // the in-memory objects. Give them room.
    testTimeout: 30_000,
  },
})
