/**
 * The PDF primitives. Every trap in CLAUDE.md F6/F8/F11/D3/D7/L6 lives here, ONCE, so no
 * call site can get it wrong.
 *
 * Deterministic. No model. No network beyond fetching the static blanks. (ARCHITECTURE §6)
 */
import {
  PDFCheckBox,
  PDFDocument,
  PDFDropdown,
  PDFName,
  PDFRadioGroup,
  PDFSignature,
  PDFTextField,
  type PDFField,
  type PDFForm,
} from 'pdf-lib'
import { NEVER_FILL } from './fieldMap'

/**
 * How the blanks are read. In the browser this is fetch(); in tests it is fs.
 * Injecting it is what lets the invariant assertions run in Node against the SAME bytes the
 * browser will use. (D5 — generation itself never leaves the tab.)
 */
export type TemplateLoader = (name: 'ENF006' | 'ENF003') => Promise<Uint8Array>

export const browserTemplateLoader: TemplateLoader = async (name) => {
  const res = await fetch(`/forms/${name}_blank.pdf`)
  if (!res.ok) throw new Error(`/forms/${name}_blank.pdf → HTTP ${res.status}`)
  return new Uint8Array(await res.arrayBuffer())
}

/**
 * A record of every field this app INTENDED to write, and with what.
 * A13 re-reads the generated bytes and asserts reality matches this exactly — no more, no
 * less. Anything the template held that we did not write is contamination. (D7)
 */
export type IntendedWrites = Map<string, string>

export type FilledDocument = {
  doc: PDFDocument
  intended: IntendedWrites
}

/**
 * D7 — MANDATORY, FIRST, EVERY TIME.
 *
 * Clears /V on the field AND /AS on every kid widget. Both, because they are different
 * things: /V is the value, /AS is the appearance state — the thing that actually renders the
 * tick. Clear only /V and you can ship a form whose value reads /Off and whose printed page
 * still shows General Partnership ticked.
 *
 * A field you do not explicitly write KEEPS WHATEVER THE TEMPLATE HAD. Do not assume the
 * template is clean. Assume it is dirty.
 */
export function zeroAllFields(form: PDFForm): void {
  for (const field of form.getFields()) {
    // NEVER touch the /Sig field's dictionary. We do not write it, and we do not clear it.
    if (field instanceof PDFSignature) continue

    const dict = field.acroField.dict
    dict.delete(PDFName.of('V'))
    dict.delete(PDFName.of('DV'))

    for (const widget of field.acroField.getWidgets()) {
      widget.dict.delete(PDFName.of('AS')) // the appearance state — the visible tick
      widget.dict.delete(PDFName.of('V'))
    }
  }
}

/** Guard: refuse to write a field we have sworn never to write. Fails closed, loudly. */
function assertWritable(name: string): void {
  if (NEVER_FILL.includes(name)) {
    throw new Error(
      `REFUSED to write "${name}". This field is on the NEVER_FILL list — it is the SSN (D3), ` +
        `a /Sig field (L6), or Date Signed. The user writes these by hand, in pen. ` +
        `If you are here to "fix a blank field", you are about to cause the exact harm the ` +
        `product exists to prevent. Stop and read CLAUDE.md.`,
    )
  }
}

/**
 * The forms' text fields carry font size 0 — "auto" — which means pdf-lib scales the text to
 * fill the box height. On the big multi-line boxes (items 19, 20, 21) that produces text an
 * inch tall, sprawling across the printed rules. It is valid, it is correct, every assertion
 * passes, and it looks like a ransom note on a government desk.
 *
 * No test catches this. Only printing it does. Pin the size.
 */
const FIELD_FONT_SIZE = 10

/**
 * Pin the font size by rewriting the field's default-appearance string.
 *
 * Why not `field.setFontSize()`: these forms were produced by Acrobat, which wrote the font
 * name in the /DA with an ESCAPED slash — `\057Helv 10 Tf 0 g` rather than `/Helv 10 Tf 0 g`.
 * pdf-lib's setFontSize() looks for a literal `/`, finds no Tf operator, and throws
 * MissingTfOperatorError. So we write the /DA ourselves, with a real slash.
 *
 * `/Helv` is in the /DR font resource of BOTH forms (ENF006 also has /ArialNarrow), and
 * flatten() renders with its own embedded Helvetica regardless, so this is consistent across
 * the packet.
 */
function pinFontSize(field: PDFTextField, size: number): void {
  field.acroField.setDefaultAppearance(`/Helv ${size} Tf 0 g`)
}

/** Write a text field, and record the intent for A13. Never blank — F6. */
export function setText(f: FilledDocument, name: string, value: string): void {
  assertWritable(name)
  const v = value.trim()
  // F6: TDLR will not process a request with blank fields. Empty → N/A.
  // (The SSN, /Sig and Date Signed are the exceptions, and assertWritable already blocked them.)
  const written = v === '' ? 'N/A' : v
  const field = f.doc.getForm().getTextField(name)
  pinFontSize(field, FIELD_FONT_SIZE)
  field.setText(written)
  f.intended.set(name, written)
}

/**
 * Tick a radio button by its TRUE PDF export value ("/Choice3").
 *
 * pdf-lib wants the bare name and throws on the slash, so we strip it — then verify the
 * value actually exists on this field before selecting, and read it back afterwards. (F8/F11)
 */
export function tickButton(f: FilledDocument, name: string, exportValue: string): void {
  assertWritable(name)
  const wanted = exportValue.replace(/^\//, '')
  const group = f.doc.getForm().getRadioGroup(name)
  const options = group.getOptions()

  if (!options.includes(wanted)) {
    throw new Error(
      `"${exportValue}" is not an option on "${name}". Actual options: ` +
        `[${options.map((o) => `/${o}`).join(', ')}]. Read data/tdlr_field_map.json. Do not guess.`,
    )
  }

  group.select(wanted)
  const readback = group.getSelected()
  if (readback !== wanted) throw new Error(`ticked "${wanted}" but "${name}" reads back "${readback}"`)

  f.intended.set(name, wanted)
}

/**
 * Leave a radio group UNTICKED. F11 — the only correct way to say "none".
 *
 * `/Off` is not a selectable value, it is the absence of one, and select('Off') throws. The
 * nearest value that WOULD work on `Type of Ownership` is `/General Partnership` — which is
 * how a man with no business ends up telling TDLR, under signature, that he is a general
 * partnership. Use this instead. Never reach for the nearest value that works.
 */
export function clearButton(f: FilledDocument, name: string): void {
  const group = f.doc.getForm().getRadioGroup(name)
  group.clear()
  // Deliberately NOT recorded in `intended`: the correct state of this field is EMPTY, and
  // A13 asserts un-intended fields are empty. Recording it would defeat the check.
}

export async function loadTemplate(
  load: TemplateLoader,
  name: 'ENF006' | 'ENF003',
): Promise<FilledDocument> {
  const doc = await PDFDocument.load(await load(name))
  const f: FilledDocument = { doc, intended: new Map() }
  zeroAllFields(doc.getForm()) // D7. First. Always. Before a single write.
  return f
}

/** Read whatever value a field holds, whatever its type. Used to verify the GENERATED BYTES. */
export function readFieldValue(field: PDFField): string | null {
  try {
    if (field instanceof PDFTextField) return field.getText() ?? null
    if (field instanceof PDFRadioGroup) return field.getSelected() ?? null
    if (field instanceof PDFCheckBox) return field.isChecked() ? 'checked' : null
    if (field instanceof PDFDropdown) return field.getSelected().join(', ') || null
    if (field instanceof PDFSignature) {
      return field.acroField.dict.has(PDFName.of('V')) ? 'SIGNED' : null
    }
  } catch {
    return null
  }
  return null
}

/**
 * Burn the text into the page content, so it prints identically on every library printer.
 * The /Sig field is present and survives this — smoke-tested. It is never populated. (L6)
 */
export function flatten(doc: PDFDocument): void {
  doc.getForm().flatten()
}
