/**
 * The assertions, run against the GENERATED BYTES.
 *
 * This module re-loads what we actually wrote — not the in-memory form object we wrote it
 * with. That distinction is the whole point. An in-memory check confirms what we INTENDED;
 * only a re-read confirms what is going in the envelope. Checking the object we just filled
 * would confirm a lie. (A13)
 */
import { PDFDocument, PDFSignature, PDFTextField } from 'pdf-lib'
import { NEVER_FILL_DATE, NEVER_FILL_SIG, NEVER_FILL_SSN } from './fieldMap'
import { readFieldValue, type IntendedWrites } from './pdfPrimitives'

export type Violation = { assertion: string; field: string; detail: string }

/**
 * Verify one filled form document, from its serialised bytes, BEFORE flattening.
 * (After flatten() there are no fields left to interrogate — which is why this runs first.)
 */
export async function verifyFilledForm(
  bytes: Uint8Array,
  intended: IntendedWrites,
  label: string,
): Promise<Violation[]> {
  const v: Violation[] = []
  const form = (await PDFDocument.load(bytes)).getForm()

  for (const field of form.getFields()) {
    const name = field.getName()
    const value = readFieldValue(field)
    const hasValue = value !== null && value !== ''

    // ── A2 — the SSN is EMPTY. Always. (D3) ────────────────────────────────────────────────
    if (NEVER_FILL_SSN.includes(name) && hasValue) {
      v.push({ assertion: 'A2', field: name, detail: `SSN field holds "${value}". It must be empty.` })
      continue
    }

    // ── A2b — the /Sig field is UNSIGNED. Always. (L6) ─────────────────────────────────────
    if (field instanceof PDFSignature || NEVER_FILL_SIG.includes(name)) {
      if (hasValue) {
        v.push({
          assertion: 'A2b',
          field: name,
          detail: 'The signature field carries a value. SurePath must NEVER sign. Wet ink only.',
        })
      }
      continue
    }

    // ── Date Signed — deliberately empty. Never "N/A" into a date they will hand-write. ────
    if (NEVER_FILL_DATE.includes(name)) {
      if (hasValue) {
        v.push({
          assertion: 'A11',
          field: name,
          detail: `Date Signed holds "${value}". It must be empty — the user dates it in ink.`,
        })
      }
      continue
    }

    // ── A13 — no field holds a value the app did not intend to write. (D7) ─────────────────
    const want = intended.get(name)
    if (want === undefined) {
      if (hasValue) {
        v.push({
          assertion: 'A13',
          field: name,
          detail:
            `holds "${value}" but the app never wrote it. This is TEMPLATE RESIDUE — ` +
            `zeroAllFields() did not do its job, and this packet would tell TDLR something ` +
            `the user never said.`,
        })
      }
      // A radio we deliberately cleared (e.g. Type of Ownership for a non-business owner)
      // lands here with no value. Correct. Nothing to assert.
      continue
    }

    if (value !== want) {
      v.push({
        assertion: 'A13',
        field: name,
        detail: `intended "${want}" but the generated bytes hold "${value}".`,
      })
    }

    // ── A11 — no blank text field in the mailed packet. (F6) ───────────────────────────────
    if (field instanceof PDFTextField && !hasValue) {
      v.push({
        assertion: 'A11',
        field: name,
        detail: 'blank text field. TDLR will not process a request with blank fields.',
      })
    }
  }

  return v.map((x) => ({ ...x, detail: `[${label}] ${x.detail}` }))
}

/** Verify the FINAL assembled packet: the text is burned in, and nothing is live or signed. */
export async function verifyAssembledPacket(bytes: Uint8Array): Promise<Violation[]> {
  const v: Violation[] = []
  const doc = await PDFDocument.load(bytes)
  const fields = doc.getForm().getFields()

  if (fields.length > 0) {
    v.push({
      assertion: 'flatten',
      field: fields.map((f) => f.getName()).join(', '),
      detail: `${fields.length} live form field(s) survived flatten(). The text is still editable.`,
    })
  }
  return v
}
