/**
 * Review & generate — the completeness wall, then the machine.
 *
 * The wall's job is COUNTING (PRD Stage 7): the count, unmissable; the offense/date/court
 * list to reconcile against the official report; the state's warnings (H3/H4, from config);
 * edit paths back into every section. Not the narratives — they were written one screen ago.
 *
 * Generation is entirely client-side (D5): draftToCase fails closed, the document service
 * verifies its own output against the generated BYTES, and a packet with violations is
 * never offered for download. The generated file lands in the Downloads folder — which
 * "Delete my information" cannot reach — so the screen says so, loudly.
 */
import { useState } from 'react'
import { Button } from '../../ui/Button'
import { FieldGroup } from '../../ui/FieldGroup'
import { Notice } from '../../ui/Notice'
import { generateAllPackets, type GeneratedPacket } from '../../documents/assemblePacket'
import { draftToCase, IncompleteDraftError } from '../convertDraft'
import { draftCounts } from '../draft'
import { formatLongDate } from '../lib/format'
import { useAppStore } from '../storeContext'

type GenState =
  | { phase: 'idle' }
  | { phase: 'working' }
  | { phase: 'incomplete'; issues: string[] }
  | { phase: 'failed'; message: string }
  | { phase: 'done'; packets: GeneratedPacket[] }

function EditLink({ sectionId, children }: { sectionId: string; children: string }) {
  const { dispatch, config } = useAppStore()
  const index = config.sections.findIndex((s) => s.id === sectionId)
  return (
    <button
      type="button"
      onClick={() => dispatch({ type: 'go', sectionId, index })}
      className="text-[13px] font-medium text-accent hover:underline"
    >
      {children}
    </button>
  )
}

export function ReviewSection() {
  const { state, config } = useAppStore()
  const [gen, setGen] = useState<GenState>({ phase: 'idle' })
  const draft = state.draft
  const a = draft.applicant
  const counts = draftCounts(draft)
  const recordsNoun =
    counts.deferrals > 0 ? 'convictions and deferred adjudications' : 'convictions'

  const generate = async () => {
    setGen({ phase: 'working' })
    try {
      const converted = draftToCase(draft, {
        agency: config.agency,
        narrativeItemLabel: config.copy.narrativeItemLabel,
      })
      const packets = await generateAllPackets(converted)
      const violations = packets.flatMap((p) => p.violations)
      if (violations.length > 0) {
        // Fail closed: a packet that failed its own verification is never offered.
        setGen({
          phase: 'failed',
          message: `Generation stopped: ${violations.length} internal check(s) failed (${violations[0].assertion}: ${violations[0].detail}). Nothing was produced. This is our bug, not your data — save your progress file so nothing is lost.`,
        })
        return
      }
      setGen({ phase: 'done', packets })
    } catch (e) {
      if (e instanceof IncompleteDraftError) {
        setGen({ phase: 'incomplete', issues: e.issues })
      } else {
        setGen({
          phase: 'failed',
          message: 'Something went wrong while assembling the packet. Your entries are safe — save your progress file and try again.',
        })
      }
    }
  }

  const download = (p: GeneratedPacket) => {
    const url = URL.createObjectURL(new Blob([p.bytes as BlobPart], { type: 'application/pdf' }))
    const el = document.createElement('a')
    el.href = url
    el.download = p.filename
    el.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex flex-col gap-8">
      {/* ── THE WALL — the count, unmissable ── */}
      <section className="rounded-[8px] border border-line bg-field px-7 py-6">
        <p className="text-[24px] font-bold leading-snug tracking-[-0.01em] text-ink">
          You have listed {counts.records} {recordsNoun} across {counts.incidents}{' '}
          {counts.incidents === 1 ? 'incident' : 'incidents'}.
        </p>
        <p className="mt-2 max-w-[62ch] text-[14.5px] leading-relaxed text-ink/80">
          Check this count against your official criminal history report. If anything is
          missing, {config.agency}'s answer may be wrong — and the real application's
          fingerprint check will find it.
        </p>
        <div className="mt-3">
          <EditLink sectionId="record">Go back and fix the record →</EditLink>
        </div>
      </section>

      <FieldGroup
        heading="Every record, counted"
        description="Offense, date, and court — reconcile each line against the report."
      >
        {draft.incidents.map((incident, i) => (
          <div key={incident.id} className="border-b border-line/60 pb-4 last:border-b-0">
            <p className="text-[12.5px] font-semibold uppercase tracking-[0.05em] text-muted">
              Incident {i + 1} · {formatLongDate(incident.dateOfConviction)} · {incident.county}{' '}
              County · {incident.court}
            </p>
            <ul className="mt-2 flex flex-col gap-1">
              {incident.charges.map((c) => (
                <li key={c.id} className="flex items-baseline justify-between gap-4 text-[14px]">
                  <span className="font-medium text-ink">{c.exactOffense}</span>
                  <span className="shrink-0 text-[12.5px] text-muted">
                    {c.disposition === 'deferred_adjudication' ? 'deferred adjudication' : 'conviction'}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </FieldGroup>

      <FieldGroup heading="Your information" description="Stamped onto every page of every packet.">
        <div className="flex items-baseline justify-between gap-4">
          <p className="text-[14.5px] leading-relaxed text-ink">
            {[a.lastName, a.firstName, a.middleName].filter(Boolean).join(', ')}
            {a.suffix && ` ${a.suffix}`} · born {a.dob}
            <span className="block text-[13.5px] text-muted">
              {a.addressStreet}, {a.addressCity}, {a.addressState} {a.addressZip} · {a.phone} ·{' '}
              {a.email}
            </span>
          </p>
          <EditLink sectionId="info">Edit</EditLink>
        </div>
      </FieldGroup>

      <FieldGroup
        heading="Your packets"
        description={`One packet and one $${config.feeUsd} money order per license type, payable to ${config.agency}.`}
      >
        <div className="flex items-baseline justify-between gap-4">
          <ul className="flex flex-col gap-1">
            {draft.licenses.map((l) => (
              <li key={`${l.program}::${l.specificLicenseType}`} className="text-[14.5px] text-ink">
                <span className="font-medium">{l.specificLicenseType}</span>
                {l.program !== l.specificLicenseType && (
                  <span className="text-muted"> — {l.program}</span>
                )}
              </li>
            ))}
            {draft.licenses.length === 0 && (
              <li className="text-[14px] text-muted">No license types chosen yet.</li>
            )}
          </ul>
          <EditLink sectionId="licenses">Edit</EditLink>
        </div>
      </FieldGroup>

      {/* ── H3/H4 — the state's warnings, plainly ── */}
      <Notice variant="info">
        <ul className="flex flex-col gap-2">
          {config.reviewWarnings.map((w) => (
            <li key={w.slice(0, 24)}>{w}</li>
          ))}
        </ul>
      </Notice>

      {/* ── generate ── */}
      <section className="border-t-2 border-line pt-7">
        {gen.phase === 'incomplete' && (
          <Notice variant="attention" title="Not ready to generate yet" className="mb-6">
            <ul className="flex flex-col gap-1">
              {gen.issues.slice(0, 5).map((issue) => (
                <li key={issue}>{issue}</li>
              ))}
              {gen.issues.length > 5 && <li>…and {gen.issues.length - 5} more.</li>}
            </ul>
          </Notice>
        )}
        {gen.phase === 'failed' && (
          <Notice variant="attention" className="mb-6">
            {gen.message}
          </Notice>
        )}

        {gen.phase === 'done' ? (
          <div>
            <p className="text-[17px] font-bold text-ink">
              {gen.packets.length === 1 ? 'Your packet is ready.' : `Your ${gen.packets.length} packets are ready.`}
            </p>
            <ul className="mt-4 flex flex-col gap-3">
              {gen.packets.map((p) => (
                <li
                  key={p.filename}
                  className="flex items-center justify-between gap-4 rounded-[8px] border border-line bg-field px-5 py-4"
                >
                  <span className="min-w-0">
                    <span className="block text-[14.5px] font-semibold text-ink">
                      {p.plan.license.specificLicenseType}
                    </span>
                    <span className="block text-[12.5px] text-muted">
                      {p.plan.mailedPages} pages to mail + your checklist · ${p.plan.feeUsd} money
                      order
                    </span>
                  </span>
                  <Button variant="primary" onClick={() => download(p)}>
                    Download
                  </Button>
                </li>
              ))}
            </ul>
            <p className="mt-5 max-w-[64ch] text-[13.5px] leading-relaxed text-ink/80">
              Page 1 of each file is your checklist — it names every place to hand-write your
              Social Security Number and every line to sign in ink. It is for you, not for the
              mail.
            </p>
            <p className="mt-2 max-w-[64ch] text-[13.5px] font-medium leading-relaxed text-ink">
              On a shared or public computer: delete the downloaded file from the Downloads
              folder after printing. "Delete my information" cannot reach files your browser
              has already saved to disk.
            </p>
          </div>
        ) : (
          <div className="flex items-center gap-4">
            <Button variant="primary" onClick={generate} disabled={gen.phase === 'working'}>
              {gen.phase === 'working' ? 'Assembling your packets…' : 'Generate my packet'}
            </Button>
            {gen.phase === 'working' && (
              <p className="text-[13px] text-muted">Filling the official forms on this computer — nothing is uploaded.</p>
            )}
          </div>
        )}
      </section>
    </div>
  )
}
